# Generated by Django 4.2.6 on 2023-10-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmarker',
            name='coordinates',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='Координаты метки'),
        ),
    ]
